baseURL: "https://asodadetective.github.io/"
title: "Asoda's Blog"
theme: "PaperMod"

enableEmoji: true

minify: 
  disableXML: true
  minifyOutput: true

params:
  defaultTheme: auto
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  
  label:
    text: Asoda

  #description: 
  profileMode:
    enabled: true
    title: "Asoda"
    subtitle: 
    imageUrl: "android-chrome-512x512.png"
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size
    buttons:
      - name: Blog
        url: archives
      # - name: Tags
        # url: tags
      # - name: About
        # url: about

    
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/asodadetective"
    - name: "RsS"
      url: "index.xml"
  
  outputs:
    home:
      - HTML 
      - RSS 
      - JSON
    
menu:
  main:
    - identifier: archives
      name: Archive
      url: archives
      weight: 1
    - identifier: tags
      name: Tags
      url: tags
      weight: 2
    - identifier: search
      name: Search
      url: search
      weight: 3
    - identifier: about
      name: About
      url: about
      weight: 4